import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ReactNode } from 'react';
import { ApolloWrapper } from './ApolloWrapper';
import PageLayout from './components/layout/PageLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
            <ApolloWrapper>
                <body className={inter.className}>
                    <PageLayout>{children}</PageLayout>
                </body>
            </ApolloWrapper>
        </html>
    );
}
